### ISSUE TITLE
Styles for Halloween

### ISSUE THREAD

**Issue by JollyJolli** [JollyJolli/HacktoberWall#133]
# New Feature: Halloween Style

## Description
I would like to create a special style for Halloween, similar to the existing dark and light modes in the application. The idea is that on October 31st, the Halloween style should be automatically applied on the client side, becoming the default style. Additionally, users should be able to switch between light, dark, and Halloween styles in a sequence: Light -> Dark -> Halloween -> Light (and repeat).

## Objectives
- Design a new visual style that reflects the Halloween theme.
- Implement a mechanism to automatically activate the Halloween style on October 31st.
- Allow users to switch between Light, Dark, and Halloween styles in the following sequence: Light -> Dark -> Halloween -> Light (and repeat).

## Tasks
- [ ] Design mockups for the new Halloween style.
- [ ] Create the CSS implementation for the Halloween style.
- [ ] Modify the client-side code to automatically apply the Halloween style on October 31st.
- [ ] Implement the switching functionality between Light, Dark, and Halloween styles.

## Considerations
- The style should be accessible and not interfere with the usability of the application.
- Ensure the user interface is intuitive for switching between styles.

**Comment by JollyJolli** [comment]
> [!NOTE]
> If you want this to be assing to you please let me know.

**Comment by TechnicallyKiller** [comment]
Assign this task to me , lemme try and figure this out my way

**Comment by JollyJolli** [comment]
Good luck!
