### ISSUE TITLE
Implement a Feedback Mechanism

### ISSUE THREAD

**Issue by JollyJolli** [JollyJolli/HacktoberWall#20]
We want to add a feedback mechanism that allows users to submit their thoughts and suggestions about the website.

### Tasks
- [x] Create a simple feedback form with fields for comments and contact information.
- [x] Implement a thank you message after form submission.
- [ ] Set up a way to collect and review the feedback submitted.

### Brief Info
User feedback is crucial for improving the website and understanding user needs.

### Additional Context
This feature will foster community engagement and help inform future updates.

**Comment by Jayesh-Waghmare** [comment]
Hi @JollyJolli I am interested in doing this work. Please could you assign it to me? ... Thank you

**Comment by JollyJolli** [comment]
Hey @Jayesh-Waghmare yes I will add you! So there is currently a form.html but there is no connection in the index to the form and there is no database

**Comment by dheerajsingh01** [comment]
hey @JollyJolli  is this issue still open ?
 it yes then i am happy to contribute .
 please check

**Comment by JollyJolli** [comment]
Yeah, you can help

**Comment by dheerajsingh01** [comment]
hey @JollyJolli  can you have a look to my feedback button 
![Screenshot 2024-10-06 143956](https://github.com/user-attachments/assets/01452526-4dda-4ae9-8ca9-42caba02dbf2)

**Comment by dheerajsingh01** [comment]
This button redirect the form.html and when user submit the form it shows a thank you message and it will redirect the index.html after 2 seconds.
can you verify it

**Comment by dheerajsingh01** [comment]
And for collecting the details which comes from form.html  we have to use a backend server and database.

**Comment by JollyJolli** [comment]
I love it

**Comment by dheerajsingh01** [comment]
hey @JollyJolli  i create a PR for the creating feedback button and connect it with form.html

**Comment by dheerajsingh01** [comment]
if want to add any backend form storing the feedback .  you can just create an issue and assign it to me.
it will take some time to do.

**Comment by JollyJolli** [comment]
Yeah dont worry, i will creat it
