### ISSUE TITLE
Add Multi-Language Support

### ISSUE THREAD

**Issue by JollyJolli** [JollyJolli/HacktoberWall#21]
Implement multi-language support to make the website accessible to non-English speakers.

### Tasks
- [ ] Identify key languages to support based on user demographics.
- [ ] Use a translation tool or service to create translations of the website content.
- [ ] Implement a language selector on the website.

### Brief Info
Offering multiple languages will broaden the audience and improve user experience.

### Additional Context
Language accessibility is essential for reaching diverse user groups.

**Comment by Potato-29** [comment]
I would like to work on this please :)

**Comment by JollyJolli** [comment]
Yes! Thank you 🫶🏻

**Comment by Phanty78** [comment]
i like to work on this feature, can you assign to me ?

**Comment by JollyJolli** [comment]
Yes of course! You could add french!

**Comment by Phanty78** [comment]
Do you know which nationalities are most represented among visitors?

**Comment by JollyJolli** [comment]
If you want edit the JSON and Send it here and I will add it, and the other HTML/JS code edit it here.

**Comment by JollyJolli** [comment]
> Do you know which nationalities are most represented among visitors?

I think is spanish and it is the main Language also

**Comment by nehaaaah123** [comment]
I would like to work on this please

**Comment by JollyJolli** [comment]
Yeah of course!

**Comment by Phanty78** [comment]
Yes, go ahead, I've already got other work to do ^^.

**Comment by Tanchuoi** [comment]
I would love to do this issue. But I'm new to this issue thing on Github. What do I need to do now?

**Comment by JollyJolli** [comment]
@Tanchuoi the file "CONTRIBUTING.md" explain it 🫶🏻
