### ISSUE TITLE
Add Back to Top Button

### ISSUE THREAD

**Issue by JollyJolli** [JollyJolli/HacktoberWall#22]
Implement a "Back to Top" button that allows users to quickly scroll back to the top of the page.

### Tasks
- [ ] Design the button using CSS.
- [ ] Use JavaScript to implement smooth scrolling functionality.
- [ ] Ensure the button is visible only when the user scrolls down.
- [ ] The button should be sticky on the down right side corner.

### Brief Info
A "Back to Top" button enhances navigation, especially on long pages.

### Additional Context
This feature improves user experience by making navigation more convenient.
Really this button will be helpful is the project ends being big.

**Comment by AACHAL2303PATIL** [comment]
I want to work on this issue, Can you assign it to me?

**Comment by JollyJolli** [comment]
Yeah of course!

**Comment by JollyJolli** [comment]
Happy contributing!

**Comment by Sanketpatil27** [comment]
hey @JollyJolli , is it still open can i work on it?

**Comment by Sanketpatil27** [comment]
thanks, @JollyJolli , please assign it under hacktoberfest

**Comment by Sanketpatil27** [comment]
Hey @JollyJolli, i have created PR, please check it!

**Comment by RijuPandey** [comment]
please assign me I really I want to work on it .Can you please assign me?
