### ISSUE TITLE
Replace alert() with Modal for Displaying Random Facts

### ISSUE THREAD

**Issue by JollyJolli** [JollyJolli/HacktoberWall#50]
#### Current Behavior
When clicking the button, a random fact is displayed using an `alert()`. The `alert()` box is used to show the fact in a pop-up.

#### Expected Behavior
Instead of using an `alert()` to show the random fact, the fact should appear inside a modal. This will allow for a more polished user experience and greater control over the display format.

### Tasks
- [ ] Remove the `alert()` function from the current implementation.
- [ ] Implement a modal to display the random fact.
- [ ] Ensure the modal opens when the button is clicked.
- [ ] Style the modal to fit the overall design of the app (basic layout and spacing).
- [ ] Ensure the modal can be closed by the user (e.g., close button or clicking outside the modal).
- [ ] Add tests to verify that the fact is correctly displayed in the modal.
- [ ] Verify cross-browser compatibility for the modal functionality.

**Comment by mishrayush15** [comment]
I can complete this task and can assure you I will create a **minimal and attractive** looking modal that would fetch and show the facts with a close button that would close the modal. For this I will be designing the modal and will be changing the ***innerHTML*** of the modal each time the modal will appear and also a Close button that will ***hide*** the modal from the webpage. I have a great experience in working with **Javascript** and can assure you I will fix this issue including all the ***verification checks*** that you have mentioned.

**Comment by JollyJolli** [comment]
Hey! Perfect! I will assign you 🫵

**Comment by mishrayush15** [comment]
Thanks a lot buddy for assigning this issue to me, will be start working on this mate ✨

**Comment by JollyJolli** [comment]
Good luck and happy contributing

**Comment by mishrayush15** [comment]
Hey Buddy! I have completed the tasks that you gave me mate. Could you please check my PR and do lemme know if that require any other changes. Have a good day!

**Comment by Phanty78** [comment]
Hello, is this contribution still available? If so, I'd be happy to take it on.

**Comment by JollyJolli** [comment]
Yeah

**Comment by Phanty78** [comment]
Has this feature been added? Should it be left open?

**Comment by JollyJolli** [comment]
Yeah, sorry, i forgot to mark this as complete, but if you want you can check the other issues or create one @Phanty78

**Comment by Phanty78** [comment]
We can close this one
